app/models.py
from . import db,login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):
    __tablename__="users"
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(255), unique = True)
    password = db.Column(db.String(255), nullable=False)
    user_image = db.Column(db.String(255))
    comments = db.relationship('Comment', backref='miradi', lazy='dynamic')
    projects = db.relationship('Project', backref='miradi', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def set_password(self, password):
        password_hash = generate_password_hash(password)
        self.password = password_hash

    def check_password(self,password):
        return check_password_hash (self.password, password)

    def __repr__(self):
        return f'User {self.username}'

@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(user_id)

class Project(db.Model):
    __tablename__="projects"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255), unique = False)
    progress = db.Column(db.Text)
    projectTimeline = db.Column(db.String(255), nullable=False)
    project_photo = db.Column(db.String(255), default='default.jpg')
    description = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable = False)
    comments = db.relationship('Comment', backref='usercomment', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Project {self.name}'

class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key = True)
    date = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    report = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable = False)
    project_id = db.Column(db.Integer, db.ForeignKey('projects.id'), nullable = False)


    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Comment {self.date}'

app/__init__.py
from flask import Flask
from config import configurations
from flask_login import login_manager,LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet,configure_uploads,IMAGES

photos = UploadSet('photos',IMAGES)
app =  Flask(__name__)
db = SQLAlchemy(app)
login_manager = LoginManager(app)
login_manager.login_view = "auth.login"
login_manager.session_protection='strong'
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app.config.from_object(configurations[config_name])
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)

    #configure uploads
    configure_uploads(app,photos)

    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from .views import *

app/main/views.py
from flask import render_template, url_for,request,redirect, abort
from flask_login import login_required,current_user, login_user, logout_user
from . import main
from .. import db, photos
from app.models import *
import requests

@main.route('/home')
@login_required
def index():
    projects =Project.query.all()
    return render_template('index.html',projects=projects)

@main.route("/")
def landing():
    projects =Project.query.all()
    return render_template('index.html',projects=projects)


@main.route('/projoprofile')
@login_required
def projoprofile():
    projects = Project.query.all()
    comments = Comment.query.all()
    return render_template('projoprofile.html', projects=projects, comments=comments)



@main.route('/projects', methods=['GET','POST'])
def projects():
    if request.method == 'POST':
        form = request.form
        name = form.get('name')
        progress = form.get('progress')
        projectTimeline = form.get('projecttimeline')
        project_photo = form .get('project_photo')
        description = form.get('description')
        if name==None or progress==None or projectTimeline==None or description==None:
            error = "Kindly fill all fields to continue"
            return render_template('projects.html', error=error)
        project = Project(name=name,progress=progress,projectTimeline=projectTimeline,project_photo=project_photo,description=description, user_id=current_user.id)
        project.save()
        return redirect(url_for('main.index'))
    return render_template('projects.html')

@main.route('/photo/<uname>', methods=['POST','GET'])
@login_required
def photo(uname):
    project = Project.query.filter_by(name=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'images/{filename}'
        project.project_photo = path
        db.session.commit()
    return redirect(url_for('main.projoprofile', uname=uname))



@main.route('/profile', methods=['POST','GET'])
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    projects = Project.query.filter_by(user_id = current_user.id).first()
    return render_template('projects.html', user=user, projects = projects)




@main.route('/comment/<int:project_id>', methods=['GET','POST'])
def comment(project_id):
    if request.method == 'POST':
        report = request.form.get('report')
        user_id = current_user.id
        project = Project.query.filter_by(id=project_id).first()
        comment = Comment(report=report,project_id=project.id,user_id=user_id)
        comment.save()
        return redirect(url_for('main.comment',project_id=project_id))
    return render_template('projoprofile.html')

app/templates/about.html
<div class="container-full">
    
</div>

app/templates/base.html
<html>
{% block styles %}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
<!--initial stylings-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/styles.css')}}">
<!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/signup.css')}}"> -->

{% endblock %}

<body>
    <!-- Insert Navbar -->

    <!-- End of Navbar -->

    {% block content %}

    {% endblock %}
    <!-- Insert scripts here -->
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
    {% endblock %}
    <!-- ENd of scripts -->
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/index.css')}}">

<section id="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Miradi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                    <!-- <a class="nav-item nav-link" href="/projects">Add Projects</a> -->
                    <!-- <a class="nav-item nav-link" href="/projoprofile">Project Profile</a> -->

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/authentication/sign-up">Register</a>
            </div>
        </div>
</nav>
    <!-- Carousel -->
    <div class="bd-example">
      <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="./static/images/kazi.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>MIRADI</h5>
              <p>Your Projects Redefined</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="./static/images/miradilogo.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>MIRADI</h5>
              <p>Lets get our leaders accountable</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
</section>

<section id="projects">
    <div class="container text-center">
        <h1>PROJECTS</h1>
    </div>
    <div class="container-fluid">
        <div class="row">
          {% for project in projects %}
            <div class="col-md-4">
                <div class="card">
                  <img src="./static/images/miradilogo.jpg" class="card-img-top w-50" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{project.name}}</h5>
                    <p class="card-text">{{project.description}}</p>
                    <p class="card-text"><small class="text-muted">{{project.user_id}}</small></p>
                  </div>
                    <div class="card-footer">
                        <a href="/projoprofile" class="btn">Read More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
</section>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/index.css')}}">


<section id="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Miradi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/projects">Add Projects</a>
                    <a class="nav-item nav-link" href="/projoprofile">Project Profile</a>

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/logout">Logout</a>
            </div>
        </div>
</nav>

    <!-- Carousel -->
    <div class="bd-example">
      <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="./static/images/kazi.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <div class="bg-dark">
                <h5>MIRADI</h5>
                <p>Your Projects Redefined</p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img src="./static/images/miradi.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block text-center">
              <div class="bg-dark">
                <h5>MIRADI</h5>
                <p>Your Projects Redefined</p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
</section>

<section id="projects">
    <div class="container text-center">
        <h1>PROJECTS</h1>
    </div>
    <div class="container-fluid">
        <div class="row">
          {% for project in projects %}
            <div class="col-md-4">
                <div class="card">
                  <img src="./static/images/miradilogo.jpg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{project.name}}</h5>
                    <p class="card-text">{{project.description | truncate(100)}}</p>
                    <p class="card-text"><small class="text-muted">{{project.user_id}}</small></p>
                  </div>
                    <div class="card-footer">
                        <a href="/projoprofile" class="btn">Read More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
</section>
    
<!-- End of Carousel -->
{% endblock %}

app/templates/login.html
{%extends 'base.html'%}
{%block content%}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/login.css')}}">

<section id="header">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Miradi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/projects">Add Projects</a>
                    <a class="nav-item nav-link" href="/projoprofile">Project Profile</a>

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/logout">Logout</a>
                <a class="nav-item nav-link" href="/authentication/sign-up">Register</a>
            </div>
        </div>
</nav>
    
</section>

<div class="container-fluid bg">
    <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-12"></div>
        <div class="col-md-4 col-sm-4 col-xs-12">
            <form class="form-container form" action="/authentication/login" method="POST">
                <h1>Login Form</h1>
                {%if error%}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
                {%endif%}
                <div class="form-group">
                        <i class="fa fa-user prefix"></i>
                        <label for="username">User Name</label>
                        <input type="text"name="username" class="form-control" required id="">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock prefix"></i>
                    <label for="password">Password</label>
                    <input type="password" class="form-control"  name="password" required id="">
                </div>
                <button class="btn btn-dark btn-block" type="submit">Login</button>
                <!-- <div class="">
                    <p class="redirect">Don't have an account? <a href="{{ url_for('auth.signup')}}">Sign-Up</a></p>
                </div> -->
                </form>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12"></div>
    </div>
    </div>
  </div>
</div>
{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Miradi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/projects">View Projects</a>
                    <a class="nav-item nav-link" href="/projoprofile">Project Profile</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/authentication/login">Login</a>
                <a class="nav-item nav-link" href="/logout">Logout</a>
                <a class="nav-item nav-link" href="/authentication/sign-up">Register</a>
            </div>
        </div>
</nav>

app/templates/projects.html
{% include 'base.html' %}


{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/signup.css')}}">

<section id="header">

   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Miradi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/projects">Add Projects</a>
                    <a class="nav-item nav-link" href="/projoprofile">Project Profile</a>


            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/logout">Logout</a>
                <a class="nav-item nav-link" href="/authentication/login">Sign Up</a>
            </div>
        </div>
</nav>
</section>

<div class="container-fluid bg">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form class="form-container form" action="/projects" method="POST">
                <h1>Register Your Projects</h1>
                {%if error%}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
                {%endif%}
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <i class="fa fa-user prefix"></i>
                            <label for="username">Name of Project</label>
                            <input class="form-control" type="text" name="name" required>
                        </div>
                        <div class="col">
                            <i class="fa fa-spinner prefix fa-spinner-hover"></i>
                            <label for="email">Project Progress</label>
                            <input class="form-control" type="text" name="progress" required>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <i class="fa fa-lock prefix"></i>
                    <label for="password">Project Timeline</label>
                    <input class="form-control" type="text" name="projecttimeline" required>
                </div>
                <div class="form-group">
                    <i class="fa fa-lock prefix"></i>
                    <label for="password">Project Description</label>
                    <textarea class="form-control" type="text" name="description" placeholder="Enter your projects dscription" required></textarea>
                </div>
                <button class="btn btn-dark btn-block" type="submit">Register</button>
                </form>
        </div>
        <div class="col-md-2"></div>
    </div>

{% endblock %}

app/templates/projoprofile.html
{% extends 'base.html' %}


{% block content %}
{{super()}}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Miradi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/projects">Add Projects</a>
                    <a class="nav-item nav-link" href="/projoprofile">Project Profile</a>

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/logout">Logout</a>
            </div>
        </div>
</nav>


  <div class="container-full pro">
    <div class="overlay">
      <div class="container">
        <div class="row">
          {% for project in projects %}
            <div class="col-md-8">
                <div class="card">
                  <!-- <img src="./static/images/kazi.jpg" class="card-img-top " alt="..." width="40%" height="40%"> -->
                  <div class="card-body">
                    <h5 class="card-title">{{project.name}}</h5>
                    <p class="card-text">{{project.prog}}</p>
                    <p class="card-text">{{project.description}}</p>
                    <p class="card-text"><small class="text-muted">{{project.user_id}}</small></p>
                  </div>
                  <div class="card-footer">
                    {% for comment in comments %}
                      <div class="card-header bg-light mt-5 pl-5">
                        <p class="text-danger">{{comment.report}}. On {{comment.date.strftime('%y-%m-%d')}}.</p>
                        <p></p>
                      </div>
                    {% endfor %}
                  </div>
                </div>
            </div>
            <div class="col-md-4">
              <div class="card">
                  <div class="card-body">
                    <form class="" action="{{url_for('main.photo',uname=project.name)}}" method="post">
                      <i class="fa fa-file-image prefix fa-3x"></i>
                      <h3>Change Project Image</h3>
                      <div class="form-group md-form">
                          <input class="form-control" type="file" name="project_photo" required>
                          <input type="submit" value="Submit">
                      </div>
                    </form>
                    <form  class="mt-3" action="{{url_for('main.projoprofile',project_id=project.id)}}" method="post">
                       <input type="text" name="report" class="w-100">
                       <input type="submit" value="Comment" class="btn btn-danger mt-1">
                    </form>
                  </div>
                </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/signup.html
{%extends 'base.html'%}
{%block content%}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/signup.css')}}">


<section id="header">

    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg sticky-top navabar-light">
            <div class="container">
                <a href="/home" class="navbar-brand">MIRADI LOGO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="#navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-iten active">
                            <a href="/authentication/login" class="nav-link">Login</a>
                        </li>
                        <li class="nav-iten active">
                            <a href="/authentication/sign-up" class="nav-link">Register</a>
                        </li>
                    </ul>
                </div>  
            </div>
        </nav>
    </div>
    
</section>
<div class="container-fluid bg">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form class="form-container form" action="/authentication/login" method="POST">
                <h1>Sign Up</h1>
                {%if error%}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
                {%endif%}
                <div class="form-group">
                        <i class="fa fa-user prefix"></i>
                        <label for="username">User Name</label>
                        <input type="text"name="username" class="form-control" required id="">
                    </div>
                <div class="form-group">
                    <i class="fa fa-envelope prefix"></i>
                    <label for="email">Email</label>
                    <input type="email"name="email" class="form-control" required id="">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock prefix"></i>
                    <label for="password">Password</label>
                    <input type="password" class="form-control"  name="password" required id="">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock prefix"></i>
                    <label for="confirm-password">Confirm Password</label>
                    <input type="password"  name="confirm_password" class="form-control" required id="">
                </div>
                <button class="btn btn-dark btn-block" type="submit">Register</button>
                </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{%endblock%}